//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Funcionario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Funcionario()
        {
            this.Incidente = new HashSet<Incidente>();
        }
    
        public string nombre { get; set; }
        public string ci { get; set; }
        public string mail { get; set; }
        public string celular { get; set; }
        public string password { get; set; }
        public int rol { get; set; }
        public string apellido { get; set; }
        public Nullable<bool> is_eliminado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Incidente> Incidente { get; set; }
        public virtual Horario Horario { get; set; }
    }
}
