//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_SRI : DbContext
    {
        public db_SRI()
            : base("name=db_SRI")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Destinatarios> Destinatarios { get; set; }
        public virtual DbSet<Funcionario> Funcionario { get; set; }
        public virtual DbSet<Horario> Horario { get; set; }
        public virtual DbSet<Incidente> Incidente { get; set; }
        public virtual DbSet<PalabraClave> PalabraClave { get; set; }

        public System.Data.Entity.DbSet<SRI.Models.IncidenteLlamado> IncidentesLlamado { get; set; }
        public System.Data.Entity.DbSet<SRI.Models.IncidenteChatWpp> IncidentesChatWpp { get; set; }
        public System.Data.Entity.DbSet<SRI.Models.IncidenteMail> IncidentesMail { get; set; }


    }
}
