//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FuncionarioVM
    {

        [Display(Name = "Apellido")]
        [Required(ErrorMessage = "Ingrese el apellido")]
        public string apellido { get; set; }

        [Display(Name = "Nombre ")]
        [Required(ErrorMessage = "Ingrese el nombre")]
        public string nombre { get; set; }

        [Display(Name = "Cedula ")]
        [Required(ErrorMessage = "Ingrese la cedula")]
        [Key]
        public string ci { get; set; }

        [Required(ErrorMessage = "Ingrese el mail")]
        [Display(Name = "Mail ")]
        [DataType(DataType.EmailAddress)]

        public string mail { get; set; }

        [Display(Name = "Celular ")]
        [Required(ErrorMessage = "Ingrese el celular")]
        public string celular { get; set; }

        [Display(Name = "Contraseña ")]
        [DataType(DataType.Password)]
        [Required(ErrorMessage = "Ingrese su contraseña")]
        public string password { get; set; }

        [Display(Name = "Horario")]
        public virtual HorarioVM Horario { get; set; }

    }
}
