//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class FuncionarioVM
    {
        public string nombre { get; set; }
        [Key]
        public string ci { get; set; }
        public string mail { get; set; }
        public string celular { get; set; }
        public string password { get; set; }
        public Rol rol { get; set; }
        public string apellido { get; set; }
        public Nullable<bool> is_eliminado { get; set; }
        public virtual HorarioVM Horario { get; set; }

    }
}
