//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    
    public partial class IncidenteVM
    {
        public IncidenteVM()
        {
            this.PalabraClave = new List<PalabraClaveVM>();
        }
    
        public int Id { get; set; }
        public System.DateTime fecha_suceso { get; set; }
        public Nullable<System.DateTime> fecha_creacion { get; set; }
        public Emocion emocion { get; set; }
        public string resolucion { get; set; }
    
        public virtual FuncionarioVM Funcionario { get; set; }
        public virtual List<PalabraClaveVM> PalabraClave { get; set; }
    }
}
