//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IncidenteMailVM : IncidenteVM
    {

        [Required(ErrorMessage = "Ingrese el asunto del mail")]
        [Display(Name = "Asunto")]
        public string asunto { get; set; }

        [Required(ErrorMessage = "Ingrese la respuesta del mail")]
        [Display(Name = "Respuesta")]
        [DataType(DataType.MultilineText)]
        public string respuesta { get; set; }

        [Required(ErrorMessage = "Ingrese el contenido del mail")]
        [Display(Name = "Contenido")]
        [DataType(DataType.MultilineText)]
        public string contenido { get; set; }

        [Required(ErrorMessage = "Ingrese el remitente del mail")]
        [Display(Name = "Remitente")]
        public string remitente { get; set; }

        [Display(Name = "Destinatarios To")]
        public string destinatariosTo { get; set; }

        [Display(Name = "Destinatarios Cc")]
        public string destinatariosCc { get; set; }



        public static explicit operator IncidenteMailVM(IncidenteMail incidenteMail)
        {
            IncidenteMailVM incidenteMailVM = new IncidenteMailVM();

            incidenteMailVM.fecha_suceso = incidenteMail.fecha_suceso;
            incidenteMailVM.fecha_creacion = incidenteMail.fecha_creacion;
            incidenteMailVM.resolucion = incidenteMail.resolucion;
            incidenteMailVM.emocion = (Emocion)incidenteMail.emocion;
            incidenteMailVM.descripcion = incidenteMail.descripcion;
            incidenteMailVM.tipo = (TipoIncidente)incidenteMail.tipo;
            incidenteMailVM.Funcionario = (FuncionarioVM)incidenteMail.Funcionario;
            incidenteMailVM.palabrasClave = incidenteMail.palabras_clave;
            incidenteMailVM.Id = incidenteMail.Id;

            incidenteMailVM.destinatariosCc = incidenteMail.destinatariosCc;
            incidenteMailVM.destinatariosTo = incidenteMail.destinatariosTo;
            incidenteMailVM.asunto = incidenteMail.asunto;
            incidenteMailVM.contenido = incidenteMail.contenido;
            incidenteMailVM.remitente = incidenteMail.remitente;
            incidenteMailVM.respuesta = incidenteMail.respuesta;


            return incidenteMailVM;
        }

    }
}
