//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IncidenteMailVM : IncidenteVM
    {

        [Required(ErrorMessage = "Ingrese el asunto del mail")]
        [Display(Name = "Asunto")]
        public string asunto { get; set; }

        [Required(ErrorMessage = "Ingrese la respuesta del mail")]
        [Display(Name = "Asunto")]
        public string respuesta { get; set; }

        [Required(ErrorMessage = "Ingrese el contenido del mail")]
        [Display(Name = "Contenido")]
        public string contenido { get; set; }

        [Required(ErrorMessage = "Ingrese la respuesta del mail")]
        [Display(Name = "Remitente")]
        public string remitente { get; set; }

        [Required(ErrorMessage = "Ingrese la respuesta del mail")]
        [Display(Name = "Destinatarios To")]
        public string destinatarioTo { get; set; }

        [Required(ErrorMessage = "Ingrese la respuesta del mail")]
        [Display(Name = "Destinatarios Cc")]
        public string destinatarioCc { get; set; }



        public static explicit operator IncidenteMailVM(IncidenteMail incidenteMail)
        {
            IncidenteMailVM incidenteMailVM = new IncidenteMailVM();

            incidenteMailVM.fecha_suceso = incidenteMail.fecha_suceso;
            incidenteMailVM.fecha_creacion = incidenteMail.fecha_creacion;
            incidenteMailVM.resolucion = incidenteMail.resolucion;
            incidenteMailVM.emocion = (Emocion)incidenteMail.emocion;
            incidenteMailVM.descripcion = incidenteMail.descripcion;
            incidenteMailVM.tipo = (TipoIncidente)incidenteMail.tipo;
            incidenteMailVM.Funcionario = (FuncionarioVM)incidenteMail.Funcionario;

            
            return incidenteMailVM;
        }

    }
}
