//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SRI.Models.ViewModels
{
    using SRI.Models.Enums;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class IncidenteLlamadoVM : IncidenteVM
    {

        [Required(ErrorMessage = "Ingrese el telefóno saliente ")]
        [Display(Name = "Teléfono saliente")]
        [DataType(DataType.PhoneNumber)]
        public string telefono_saliente { get; set; }

        [Required(ErrorMessage = "Ingrese el teléfono entrante")]
        [Display(Name = "Teléfono entrante")]
        [DataType(DataType.PhoneNumber)]
        public string telefono_entrante { get; set; }

        [Required(ErrorMessage = "Ingrese la hora de inicio")]
        [Display(Name = "Hora inicio")]
        [DataType(DataType.Time)]
        public System.DateTime hora_inicio { get; set; }

        [Required(ErrorMessage = "Ingrese la hora de fin")]
        [Display(Name = "Hora fin")]
        [DataType(DataType.Time)]
        public System.DateTime hora_fin { get; set; }

        [Required(ErrorMessage = "Ingrese el nombre de la persona que llama")]
        [Display(Name = "Nombre persona que llama")]
        public string nombre_persona_llama { get; set; }

        public static explicit operator IncidenteLlamadoVM(IncidenteLlamado incidenteLlamado)
        {
            IncidenteLlamadoVM incidenteLlamadoVM = new IncidenteLlamadoVM();

            incidenteLlamadoVM.fecha_suceso = incidenteLlamado.fecha_suceso;
            incidenteLlamadoVM.fecha_creacion = incidenteLlamado.fecha_creacion;
            incidenteLlamadoVM.resolucion = incidenteLlamado.resolucion;
            incidenteLlamadoVM.emocion = (Emocion)incidenteLlamado.emocion;
            incidenteLlamadoVM.descripcion = incidenteLlamado.descripcion;
            incidenteLlamadoVM.tipo = (TipoIncidente)incidenteLlamado.tipo;
            incidenteLlamadoVM.Funcionario = (FuncionarioVM)incidenteLlamado.Funcionario;

            incidenteLlamadoVM.telefono_entrante = incidenteLlamado.telefono_entrante;
            incidenteLlamadoVM.telefono_saliente = incidenteLlamado.telefono_saliente;
            incidenteLlamadoVM.hora_inicio = incidenteLlamado.hora_inicio;
            incidenteLlamadoVM.hora_fin = incidenteLlamado.hora_fin;
            incidenteLlamadoVM.nombre_persona_llama = incidenteLlamado.nombre_persona_llama;


            return incidenteLlamadoVM;
        }
    }
}
